project:
  type: website
  post-render:
    - "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352

website:
  title: "Alexander Hurley"
  site-url: https://aglhurley.rbind.io
  description: "Environmental data scientist advising on climate change mitigation policy and open science advocate."
  favicon: ""
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@aglhurley"
    site: "@aglhurley"
    card-style: summary_large_image
 
 
  navbar:
    logo: ""
    tools:
    - icon: github
      href: https://www.github.com/the-hull/aglhurley
    right:
      - text: About
        aria-label: "About Me"
        href: about/index.qmd
      - text: Blog
        aria-label: "Stepping stones with R and python"
        href: blog/index.qmd
      - text: Talks
        aria-label: "Talks and Workshops"
        href: talk/index.qmd  
      - text: Publications
        aria-label: "Publications"
        href: publication/index.qmd
      - text: Projects
        aria-label: "Projects"
        href: project/index.qmd
  
  page-footer:  
    left: >-
     &#169; 2024 Alexander Hurley &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="https://linkedin.com/in/aglhurley" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/the-hull" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0002-9641-2805" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=plLuAz0AAAAJ&hl=en&oi=ao" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      

    right: 
    
      - text: "Contact"
        aria-label: "Contact Form"
        href: "contact.qmd"
      - text: "License"
        aria-label: "License Details"
        href: license.qmd
      - icon: rss
        href: blog/index.xml

format: 
  html:
    theme:
      light:
        - cosmo
        - assets/fin-theme-light.scss
        - assets/colors.scss
        - assets/fonts/fonts.scss
      dark: 
        - cosmo
        - assets/fin-theme-dark.scss
        - assets/fonts/fonts.scss
        - assets/colors.scss

    # highlight-style:
    #   light: 
    #   dark: 
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute: 
  freeze: auto

