---
title: "Legacy effects in radial tree growth are rarely significant after accounting for biological memory"

author: ["Stefan Klesse", "Flurin Babst", "Margaret E. K. Evans", {name: "**Alexander Hurley**", orcid: 0000-0002-9641-2805}, "Christoforos Pappas", "Richard L. Peters"]


date: "2022-11-23"

slug: je-legacy-effects

categories: 
  - research

tags: 
  - auto-correlation
  - time series analyses
  


featured: yes


publication: "*Journal of Ecology*"


links:
- icon: doi
  icon_pack: ai
  name: Publication
  url: https://doi.org/10.1111/1365-2745.14045
- icon: laptop-code
  name: Code
  url: https://doi.org/10.6084/m9.figshare.21493563.v1



---

## Abstract


1. Drought legacies in radial tree growth are an important feature of variability in biomass accumulation and are widely used to characterize forest resilience to climate change. Defined as a deviation from normal growth, the statistical significance of legacy effects depends on the definition of “normal”—expected growth under average conditions—which has not received sufficient scrutiny.
2. We re-examined legacy effect analyses using the International Tree-Ring Data Bank (ITRDB) and then produced synthetic tree-ring data to disentangle four key variables influencing the magnitude of legacy effects. We hypothesized that legacy effects (i) are mainly influenced by the auto-correlation of the radial growth time series (phi), (ii) depend on climate-growth cross-correlation (rho), (iii) are directly proportional to the inherent variability of the growth time series (standard deviation, SD), and (iv) scale with the chosen extreme event threshold.
3. Using a data simulation approach, we were able to reproduce observed lag patterns, demonstrating that legacy effects are a direct outcome of ubiquitous biological memory. We found that stronger legacy effects for conifers compared to angiosperms is a consequence of their higher auto-correlation, and that the detectability of legacy effects following rare drought events at individual sites is compromised by strong background stochasticity.
4. Synthesis. We propose two pathways forward to improve the assessment and interpretation of legacy effects: First, we highlight the need to account for auto-correlated residuals of climate-growth regression models a posteriori, thereby retrospectively adjusting expectations for “normal” growth variability. Alternatively, we recommend including lagged climate variables in regression models a priori. By doing so, the magnitude of detected legacy effects is greatly reduced and biological memory is directly attributed to antecedent climatic drivers. We argue that future analyses should focus on understanding the functional reasons for how and why key statistical parameters describing this biological memory differ across species and sites. These two pathways should also stimulate improved process-based representation of vegetation carbon dynamics in mechanistic models.
