---
title: On reproducibility of computational methods and analyses
author: ''
date: '2019-06-05'
slug: on-reproducibility-part-i
categories:
  - Data Science
  - R
tags:
  - R
  - tidyverse
  - r-dev
  - packages
header:
  caption: ''
  image: ''
  preview: yes
---

## Reproducibility is key

Reproducibility is one key aspect of the scientific method, and approaches to guarantee it are continuously developed and improved upon. 
While reproducing results is one (final) and highly desirable goal of the reproducibility agenda, it all starts with raw data, and a some steps to get to a final outcome (e.g. model output and diagnostics, visualization, etc.). 
These steps typically require dedicated software, together with a "recipe".


`R` as a (statistical) programming language provides the backbone for many an analyses.
Scripts, together with dedicated 'third-party' packages allow in-depth and elaborate analyses to address hypotheses. 
While any researcher can derive insights with the aforementioned set-up, it takes quite some skill to reproduce the data and folder structure and to generate the same outputs on a different computer, especially after some time, after software versions changed.   
There are multiple methods to address these issues, and upcoming posts will deal with approaches (of varying complexity) to allow an entire analyses (from raw data to final report/publication) to be reproduced by anyone (with a little bit of computing knowledge).


### Part 1 - Research Compendia

- [Post](https://the-hull.github.io/reproducibility_compendium/analyses/00_write-up.html)
- [GitHub repository (compendium)](https://github.com/the-Hull/reproducibility_compendium/)